services:
  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    container_name: zipkin
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE = mem
    restart: always
    networks:
      - gateway


  config-server:
    build:
      context: ConfigurationService
      dockerfile: Dockerfile
    container_name: config-server
    image: config-server:1.0
    ports:
      - "8888:8888"
    restart: always

  discovery-server:
    build:
      context: DiscoveryService
      dockerfile: Dockerfile
    container_name: discovery-server
    image: discovery-server:1.0
    ports:
      - "8761:8761"
    restart: always
    depends_on:
      - zipkin
      - config-server
    networks:
      - gateway

  api_gateway:
    build:
      context: Api-Gateway
      dockerfile: Dockerfile
    container_name: api_gateway
    image: api_gateway:1.0
    ports:
      - "8000:8000"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - environments/apigateway.env
    restart: always
    depends_on:
      - discovery-server
      - config-server
      - zipkin
    networks:
      - gateway


  # ================================== Authenticate-DB & AuthService ==================================

  AuthenticateService:
    build:
      context: AuthService
      dockerfile: Dockerfile
    container_name: Authenticate_Service
    image: authenticate-service:1.0
    ports:
      - "8010:8010"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - environments/authenticate.env
    restart: always
    depends_on:
      - zipkin
      - config-server
      - discovery-server
      - api_gateway
    networks:
      - gateway

    # ================================== Student-DB & StudentService ==================================

  StudentService:
    build:
      context: StudentService
      dockerfile: Dockerfile
    container_name: StudentService
    image: student-service:1.0
    ports:
      - "8020:8020"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - environments/student.env
    restart: always
    depends_on:
      - zipkin
      - config-server
      - discovery-server
      - api_gateway
    networks:
      - gateway

    # ================================== Class-DB & ClassService ==================================

  ClassService:
    build:
      context: ClassService
      dockerfile: Dockerfile
    container_name: ClassService
    image: class-service:1.0
    ports:
      - "8030:8030"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - environments/class.env
    restart: always
    depends_on:
      - zipkin
      - config-server
      - discovery-server
      - api_gateway
    networks:
      - gateway

    # ================================== Course-DB & CourseService ==================================

  CourseService:
    build:
      context: CourseService
      dockerfile: Dockerfile
    container_name: CourseService
    image: course-service:1.0
    ports:
      - "8040:8040"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - environments/course.env
    restart: always
    depends_on:
      - zipkin
      - config-server
      - discovery-server
      - api_gateway
    networks:
      - gateway

    # ================================== Enrollment-DB & EnrollmentService ==================================

  EnrollmentService:
    build:
      context: EnrollmentService
      dockerfile: Dockerfile
    container_name: EnrollmentService
    image: enrollment-service:1.0
    ports:
      - "8050:8050"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - environments/enrollment.env
    restart: always
    depends_on:
      - zipkin
      - config-server
      - discovery-server
      - api_gateway
    networks:
      - gateway

    # ================================== Graduation-DB & GraduationService ==================================

  GraduationService:
    build:
      context: GraduationService
      dockerfile: Dockerfile
    container_name: GraduationService
    image: graduation-service:1.0
    ports:
      - "8060:8060"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - environments/graduation.env
    restart: always
    depends_on:
      - zipkin
      - config-server
      - discovery-server
      - api_gateway
    networks:
      - gateway

    # ================================== LearningResult-DB & LearningResultService ==================================

  LearningResultService:
    build:
      context: LearningResultService
      dockerfile: Dockerfile
    container_name: LearningResultService
    image: learningresult-service:1.0
    ports:
      - "8070:8070"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - environments/learningresult.env
    restart: always
    depends_on:
      - zipkin
      - config-server
      - discovery-server
      - api_gateway
    networks:
      - gateway

    # ================================== Schedule-DB & ScheduleService ==================================

  ScheduleService:
    build:
      context: ScheduleService
      dockerfile: Dockerfile
    container_name: ScheduleService
    image: schedule-service:1.0
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - environments/schedule.env
    restart: always
    depends_on:
      - zipkin
      - config-server
      - discovery-server
      - api_gateway
    networks:
      - gateway

networks:
  gateway:




