FROM eclipse-temurin:17-jdk-alpine
COPY build/libs/LearningResultService-0.0.1-SNAPSHOT.jar LearningResultService-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/LearningResultService-0.0.1-SNAPSHOT.jar"]